import React from 'react';
import styles from './InvoiceInputPanel.module.css';

const InvoiceInputPanel = ({
  clientId, setClientId,
  invoiceDate, setInvoiceDate,
  dueDate, setDueDate,
  paymentMethod, setPaymentMethod,
  status, setStatus,
  taxRate, setTaxRate,
  discount, setDiscount,
  generatedBy, setGeneratedBy,
  notes, setNotes
}) => {
  return (
    <div className={styles.panel}>
      <h2 className={styles.heading}>Invoice Details</h2>

      <div className={styles.inputGroup}>
        <label>Client ID:</label>
        <input type="text" value={clientId} onChange={e => setClientId(e.target.value)} />
      </div>

      <div className={styles.inputGroup}>
        <label>Invoice Date:</label>
        <input type="date" value={invoiceDate} onChange={e => setInvoiceDate(e.target.value)} />
      </div>

      <div className={styles.inputGroup}>
        <label>Due Date:</label>
        <input type="date" value={dueDate} onChange={e => setDueDate(e.target.value)} />
      </div>

      <div className={styles.inputGroup}>
        <label>Payment Method:</label>
        <select value={paymentMethod} onChange={e => setPaymentMethod(e.target.value)}>
          <option>Cash</option>
          <option>Credit Card</option>
          <option>Bank Transfer</option>
          <option>UPI</option>
        </select>
      </div>

      <div className={styles.inputGroup}>
        <label>Status:</label>
        <select value={status} onChange={e => setStatus(e.target.value)}>
          <option>Unpaid</option>
          <option>Paid</option>
          <option>Pending</option>
        </select>
      </div>

      <div className={styles.inputGroup}>
        <label>Tax Rate (%):</label>
        <input type="number" value={taxRate} onChange={e => setTaxRate(e.target.value)} />
      </div>

      <div className={styles.inputGroup}>
        <label>Discount (%):</label>
        <input type="number" value={discount} onChange={e => setDiscount(e.target.value)} />
      </div>

      <div className={styles.inputGroup}>
        <label>Generated By:</label>
        <input type="text" value={generatedBy} onChange={e => setGeneratedBy(e.target.value)} />
      </div>

      <div className={styles.inputGroup}>
        <label>Notes:</label>
        <textarea value={notes} onChange={e => setNotes(e.target.value)} />
      </div>
    </div>
  );
};

export default InvoiceInputPanel;
